SELECT * FROM flights WHERE origin = 'New York';
SELECT destination, duration FROM flights WHERE origin = 'New York';
SELECT destination, duration FROM flights WHERE duration > 500;
SELECT destination, duration FROM flights WHERE duration > 500 AND destination = 'Paris';
SELECT AVG(duration) FROM flights;
SELECT AVG(duration) FROM flights WHERE origin = 'New York';
SELECT COUNT(*) FROM flights;
SELECT COUNT(*) FROM flights WHERE origin = 'New York';
SELECT MIN(duration) FROM flights;
SELECT * FROM flights WHERE origin IN ('New York', 'Lima');
SELECT * FROM flights LIMIT 2;
SELECT * FROM flights ORDER BY origin;
SELECT * FROM flights ORDER BY duration DESC LIMIT 2;
SELECT * FROM flights ORDER BY duration ASC LIMIT 2;
SELECT origin, COUNT(*) FROM flights GROUP BY origin;
SELECT origin, COUNT(*) FROM flights GROUP BY origin HAVING COUNT(*) > 1;
SELECT origin, destination, name FROM flights INNER JOIN passangers ON passangers.flight_id = flights.id WHERE name = 'Alice';
SELECT flight_id FROM passangers GROUP BY flight_id HAVING COUNT(*) > 1;
SELECT * FROM flights WHERE id IN (SELECT flight_id FROM passangers GROUP BY flight_id HAVING COUNT(*) > 1);